### ISSUE TITLE
Updates do not seem to be applied correctly

### ISSUE THREAD

**Issue by mirodrr** [maxtybar/bedrock-agents-cdk#6]
I have tried updating the "instruction" and the "agentResourceRoleArn" on the BedrockAgent construct, and it doesn't seem to work at all. I have to completely destroy and recreate the stack for it to take effect

**Steps to reproduce:**

1. Deploy this example from the readme:

```
import * as cdk from 'aws-cdk-lib';
import { BedrockAgent } from 'bedrock-agents-cdk';

const app = new cdk.App();
const stack = new cdk.Stack(app, 'BedrockAgentStack');

const agent = new BedrockAgent(stack, "BedrockAgent", {
  agentName: "BedrockAgent",
  instruction: "This is a test instruction. You were built by AWS CDK construct to answer all questions.",
})
```

2. Edit the instruction:

```
import * as cdk from 'aws-cdk-lib';
import { BedrockAgent } from 'bedrock-agents-cdk';

const app = new cdk.App();
const stack = new cdk.Stack(app, 'BedrockAgentStack');

const agent = new BedrockAgent(stack, "BedrockAgent", {
  agentName: "BedrockAgent",
  instruction: "This is a new test instruction.",
})
```

3. Redeploy

4. Observe that the change does not take effect

**Comment by maxtybar** [comment]
@mirodrr Yes, this is not an error as updates are not implemented as of right now. I will consider adding this in the future.

**Comment by mirodrr** [comment]
Okay, that's no problem. But I would appreciate it if it was documented in the ReadMe at least. Was confusing.

**Comment by maxtybar** [comment]
Closing this due to retiring the repo and contributing to another managed project.

Please refer to the [generative-ai-cdk-constructs](https://github.com/awslabs/generative-ai-cdk-constructs/tree/main) repo for the latest constructs. I don't have currently time to maintain my construct and will focus my attention on contributing to the mentioned repo as it is maintained by the AWS team.

Thanks!
